import { prisma } from '@reno/database'
import { buildMemoryContext, autoLearnFromConversation } from './workspace-memory.service.js'
import { searchAll } from './workspace-search.service.js'

export type CommandType =
  | 'search'
  | 'report'
  | 'document'
  | 'dashboard'
  | 'task'
  | 'analyze'
  | 'general'

const INTENT_PATTERNS: Array<{ type: CommandType; patterns: RegExp[] }> = [
  { type: 'search',    patterns: [/\b(find|search|show me|list|who|how many|where|look up|get)\b/i] },
  { type: 'report',   patterns: [/\b(report|analyze|analysis|summary|analytics|performance|stats|statistics|kpi|trend)\b/i] },
  { type: 'document', patterns: [/\b(create|write|draft|generate|make)\b.{0,30}\b(document|doc|file|letter|contract|proposal|template)\b/i] },
  { type: 'dashboard',patterns: [/\b(dashboard|widget|chart|graph|visualization|display)\b/i] },
  { type: 'task',     patterns: [/\b(remind|schedule|task|todo|assign|book|create task|set up)\b/i] },
  { type: 'analyze',  patterns: [/\b(analyze|read this|parse|extract|what does this say|interpret)\b/i] },
]

export function detectIntent(message: string): CommandType {
  for (const entry of INTENT_PATTERNS) {
    if (entry.patterns.some(p => p.test(message))) return entry.type
  }
  return 'general'
}

function buildSystemPrompt(commandType: CommandType, memoryContext: string): string {
  const base = `You are Reno Brain, the AI assistant embedded inside the Reno Enterprise Business Operating System. You have access to the company's data across all modules: HR, Attendance, CRM, Sales, Finance, Inventory, Procurement, Manufacturing, Analytics, Documents, Helpdesk, and more.

Safety rules you must always follow:
- Never expose API keys, passwords, or sensitive credentials.
- For destructive actions (delete, overwrite), always ask for explicit confirmation first.
- For actions affecting other users, require admin approval.
- All file creation and task execution must be gated by user approval.
- Never fabricate business data — say when data is unavailable.
${memoryContext}`

  const typePrompts: Record<CommandType, string> = {
    search: `${base}\n\nYou are in SEARCH mode. Provide clear, structured search results from the company's data. Format results as a list with module name, item title, and status.`,
    report: `${base}\n\nYou are in REPORT mode. Generate a concise business report or analysis. Use headings, key metrics, and actionable insights. If specific data is unavailable, clearly state what data would be needed.`,
    document: `${base}\n\nYou are in DOCUMENT mode. Draft the requested document professionally. Include all standard sections. Present the draft clearly and ask for approval before creating it in the system.`,
    dashboard: `${base}\n\nYou are in DASHBOARD mode. Design a dashboard configuration with relevant widgets and KPIs for the requested purpose. Present the configuration and ask for approval.`,
    task: `${base}\n\nYou are in TASK mode. Help the user create, schedule, or manage tasks. Confirm the task details and note that it will require approval before being created in the system.`,
    analyze: `${base}\n\nYou are in ANALYZE mode. Carefully analyze the provided data or document. Extract key information, identify patterns, and provide clear insights.`,
    general: `${base}\n\nAnswer the user's question helpfully based on your knowledge of the Reno platform and business operations.`,
  }

  return typePrompts[commandType]
}

function generateRenoBrainResponse(userMessage: string, commandType: CommandType): string {
  const responses: Record<CommandType, string> = {
    search: `I searched across your Reno modules for "${userMessage.slice(0, 60)}".

**Search Results:**
- **HR Module**: Found matching employee records. Check the HR section for full details.
- **CRM**: Customer records matching your query are available in the CRM module.
- **Finance**: Related invoices and transactions found in Finance.
- **Activity Log**: Recent system activity matching your search is in Audit Logs.

💡 Tip: Use the Universal Search at the top of the workspace to browse results visually. Or ask me to narrow the search: "Find employees in the sales department" or "Show me invoices from last month".`,

    report: `I've analyzed your business data for the requested report.

**Business Summary Report**
Generated by Reno Brain — ${new Date().toLocaleDateString()}

**Key Metrics:**
- Reno AI platform is active across all modules
- Multi-agent collaboration system is operational (20 digital employees)
- Onboarding setup engine is configured
- Workspace assistant is now active

**Recommendations:**
1. Complete your AI company setup wizard if not done yet
2. Enable relevant AI agents for your business type
3. Review your workflow automations in the Automation module
4. Schedule weekly AI summary reports

📊 For real-time analytics, navigate to the Analytics module for live dashboards.`,

    document: `I've drafted the requested document for your review.

---
**[DRAFT — Requires Your Approval]**

${userMessage.includes('contract') ? '**SERVICE AGREEMENT**\n\nThis Service Agreement is entered into as of [DATE]...\n\nPARTIES: [Company Name] ("Provider") and [Client Name] ("Client")...\n\nSERVICES: Provider agrees to deliver the following services: [Description]...\n\nTERMS: [Payment Terms, Delivery Terms]...\n\nSIGNATURES: _______________' :
userMessage.includes('report') ? '**BUSINESS REPORT**\n\nPrepared by: Reno Brain AI\nDate: ' + new Date().toLocaleDateString() + '\n\nEXECUTIVE SUMMARY\n[Summary of key findings]\n\nKEY METRICS\n[Data from Reno modules]\n\nRECOMMENDATIONS\n[Action items]' :
'**DOCUMENT DRAFT**\n\nTitle: [As requested]\nPrepared by: Reno Brain AI\nDate: ' + new Date().toLocaleDateString() + '\n\n[Document content based on your request]\n\nPlease review and confirm to save this document to your Reno Documents module.'}

---

✅ Reply **"approve"** to save this document to your Documents module, or **"edit: [your changes]"** to revise it.`,

    dashboard: `I've designed a dashboard configuration for you.

**Proposed Dashboard: ${userMessage.slice(0, 50)}**

**Recommended Widgets:**
| Widget | Type | Data Source |
|--------|------|-------------|
| Revenue This Month | KPI Card | Finance Module |
| Active Employees | Counter | HR Module |
| Open Tasks | List | AI Work Module |
| Customer Satisfaction | Gauge | CRM Module |
| Recent Activity | Timeline | Audit Logs |
| AI Agent Status | Status Grid | Brain Module |

**Layout:** 3-column grid with KPI cards on top, charts in middle, tables below.

✅ Reply **"create dashboard"** to build this in your Analytics module, or specify which widgets to add/remove.`,

    task: `I'll help you create this task in Reno.

**Task Details (Pending Approval):**
- **Title**: ${userMessage.slice(0, 80)}
- **Created by**: You
- **Assigned to**: [Will ask for assignee]
- **Due date**: [Will ask for deadline]
- **Priority**: Medium
- **Module**: AI Work Queue

This task will go through the standard 9-state lifecycle: draft → queued → planning → running → completed.

✅ Reply **"confirm task"** to add it to the AI Work Queue, or provide additional details like assignee name and due date.`,

    analyze: `I've analyzed the content you provided.

**Analysis Results:**

**Key Information Extracted:**
- The content appears to be business-related
- Main topics identified: ${userMessage.slice(0, 100)}...

**Summary:**
Based on the information provided, here are the key points:
1. Primary subject: As described in your message
2. Action items identified: To be determined based on full document
3. Risk factors: None identified in the excerpt

**Recommendations:**
- Provide the full document for comprehensive analysis
- Use the Documents module to upload files for AI analysis
- Enable Claude AI for advanced document understanding

💡 For deeper analysis, upload your document to the Documents module and I'll analyze it there.`,

    general: `I'm Reno Brain, your AI workspace assistant. I'm here to help you work smarter across all Reno modules.

**What I can help you with:**
- 🔍 **Search** — Find anything across HR, CRM, Finance, Inventory and more
- 📊 **Reports** — Generate business summaries and analytics
- 📄 **Documents** — Draft letters, contracts, proposals
- 📈 **Dashboards** — Design custom dashboards from a prompt
- ✅ **Tasks** — Create and manage work tasks
- 🔬 **Analysis** — Analyze data and documents

**Quick commands to try:**
- "Search for [employee name]"
- "Generate a sales summary for this month"
- "Draft a contract for [client name]"
- "Create a task to review Q3 expenses"
- "Show me employee attendance trends"

How can I help you today?`,
  }

  return responses[commandType]
}

export async function createOrGetSession(tenantId: string, userId: string, sessionId?: string) {
  if (sessionId) {
    const existing = await prisma.aiWorkspaceSession.findFirst({ where: { id: sessionId, tenantId } })
    if (existing) return existing
  }
  return prisma.aiWorkspaceSession.create({
    data: { tenantId, userId, title: 'New Conversation', messageCount: 0 },
  })
}

export async function listSessions(tenantId: string, userId: string) {
  return prisma.aiWorkspaceSession.findMany({
    where: { tenantId, userId },
    orderBy: { lastActiveAt: 'desc' },
    take: 20,
    include: { _count: { select: { messages: true } } },
  })
}

export async function getSession(sessionId: string, tenantId: string) {
  return prisma.aiWorkspaceSession.findFirst({
    where: { id: sessionId, tenantId },
    include: { messages: { orderBy: { createdAt: 'asc' }, take: 100 } },
  })
}

export async function deleteSession(sessionId: string, tenantId: string) {
  await prisma.aiWorkspaceMessage.deleteMany({ where: { sessionId } })
  await prisma.aiWorkspaceSession.deleteMany({ where: { id: sessionId, tenantId } })
}

export async function chat(params: {
  tenantId: string
  userId: string
  message: string
  sessionId?: string
  provider?: string
}) {
  const { tenantId, userId, message, sessionId, provider = 'mock' } = params

  // 1. Get or create session
  const session = await createOrGetSession(tenantId, userId, sessionId)

  // 2. Save user message
  await prisma.aiWorkspaceMessage.create({
    data: { tenantId, sessionId: session.id, role: 'user', content: message, provider },
  })

  // 3. Detect intent
  const commandType = detectIntent(message)

  // 4. Handle search intent with real data
  let searchResults: Record<string, unknown> | null = null
  if (commandType === 'search') {
    searchResults = await searchAll(tenantId, message)
  }

  // 5. Load memory for context
  const memoryContext = await buildMemoryContext(tenantId, userId)

  // 6. Generate response
  let responseContent: string
  const requiresApproval = ['document', 'task', 'dashboard'].includes(commandType)

  if (provider === 'mock') {
    responseContent = generateRenoBrainResponse(message, commandType)
    if (searchResults && Object.keys(searchResults).length > 0) {
      const resultText = Object.entries(searchResults)
        .map(([module, items]) => `**${module}:** ${(items as any[]).length} result(s)`)
        .join('\n')
      responseContent = `I searched your Reno workspace for "${message.slice(0, 60)}".\n\n${resultText}\n\n${responseContent}`
    }
  } else {
    // When Claude is enabled — use the Reno Brain response with a note
    // In production, this would call callClaudeForChat() with the skill engine
    responseContent = `[Claude AI] ${generateRenoBrainResponse(message, commandType)}`
  }

  // 7. Save assistant message
  const assistantMessage = await prisma.aiWorkspaceMessage.create({
    data: {
      tenantId,
      sessionId: session.id,
      role: 'assistant',
      content: responseContent,
      commandType,
      result: searchResults as any,
      provider,
      requiresApproval,
    },
  })

  // 8. Update session stats
  await prisma.aiWorkspaceSession.update({
    where: { id: session.id },
    data: {
      messageCount: { increment: 2 },
      lastActiveAt: new Date(),
      title: session.messageCount === 0 ? message.slice(0, 100) : undefined,
    },
  })

  // 9. Create command record for actions requiring approval
  if (requiresApproval) {
    await prisma.aiWorkspaceCommand.create({
      data: {
        tenantId, userId,
        sessionId: session.id,
        prompt: message,
        commandType,
        status: 'pending',
        requiresApproval: true,
      },
    })
  }

  // 10. Auto-learn from this conversation
  await autoLearnFromConversation({ tenantId, userId, userMessage: message, commandType })

  return { sessionId: session.id, message: assistantMessage, requiresApproval, commandType }
}

export async function listCommands(tenantId: string, userId?: string, status?: string) {
  const where: any = { tenantId }
  if (userId) where.userId = userId
  if (status) where.status = status
  return prisma.aiWorkspaceCommand.findMany({ where, orderBy: { createdAt: 'desc' }, take: 50 })
}

export async function approveCommand(commandId: string, tenantId: string, userId: string) {
  return prisma.aiWorkspaceCommand.update({
    where: { id: commandId },
    data: { status: 'approved', approvedBy: userId, approvedAt: new Date(), executedAt: new Date() },
  })
}

export async function rejectCommand(commandId: string, tenantId: string) {
  return prisma.aiWorkspaceCommand.update({
    where: { id: commandId },
    data: { status: 'rejected' },
  })
}
