import type { FastifyInstance } from 'fastify'
import { authRoutes } from './auth.routes.js'
import { userRoutes } from './users.routes.js'
import { orgRoutes } from './org.routes.js'
import { roleRoutes } from './roles.routes.js'
import { settingsRoutes } from './settings.routes.js'
import { auditRoutes } from './audit.routes.js'
import { notificationRoutes } from './notifications.routes.js'
import { translationRoutes } from './translations.routes.js'
import { aiUsageRoutes } from './ai-usage.routes.js'
import { hrRoutes } from './hr/index.js'
import { pmRoutes } from './pm/index.js'
import { crmRoutes } from './crm/index.js'
import { salesRoutes } from './sales/index.js'
import { financeRoutes } from './finance/index.js'
import { inventoryRoutes } from './inventory/index.js'
import { procurementRoutes } from './procurement/index.js'
import { manufacturingRoutes } from './manufacturing/index.js'
import { analyticsRoutes } from './analytics/index.js'
import { brainRoutes } from './brain/index.js'
import { automationRoutes } from './automation/index.js'
import { docsRoutes } from './docs/index.js'
import { kbRoutes } from './kb/index.js'
import { portalRoutes } from './portal/index.js'
import { helpdeskRoutes } from './helpdesk/index.js'
import { commRoutes } from './comm/index.js'
import { marketplaceRoutes } from './marketplace/index.js'
import { aiExecRoutes } from './ai-exec/index.js'
import { securityRoutes } from './security/index.js'
import { monitoringRoutes } from './monitoring/index.js'
import { backupRoutes } from './backup/index.js'
import { drRoutes } from './dr/index.js'
import { aiSreRoutes } from './ai-sre/index.js'
import { deploymentRoutes } from './deployment/index.js'
import { developerRoutes } from './developer/index.js'
import { adminAiProviderRoutes } from './admin/ai-providers.routes.js'
import { aiWorkRoutes } from './ai-work/index.js'
import { aiAgentsRoutes } from './ai-agents/index.js'
import { aiOnboardingRoutes } from './ai-onboarding/index.js'
import { aiWorkspaceRoutes } from './ai-workspace/index.js'
import { realtimeRoutes } from './events/index.js'
import { globalSearchRoutes } from './search/index.js'
import { ssoModuleRoutes } from './sso/index.js'
import { reportBuilderRoutes } from './reports/index.js'
import { wlRoutes } from './whitelabel/index.js'
import { cdpModuleRoutes } from './cdp/index.js'
import { mktRoutes } from './marketing/index.js'
import { dataHubModuleRoutes } from './data-hub/index.js'
import { mobileModuleRoutes } from './mobile/index.js'
import { partnerModuleRoutes } from './partners/index.js'
import { forecastModuleRoutes } from './forecasting/index.js'
import { fxModuleRoutes } from './fx/index.js'
import { clmModuleRoutes } from './clm/index.js'
import { fsmModuleRoutes } from './fsm/index.js'
import { vendorModuleRoutes } from './vendors/index.js'
import { lmsModuleRoutes } from './lms/index.js'
import { assetModuleRoutes } from './assets/index.js'
import { complianceModuleRoutes } from './compliance/index.js'
import { csModuleRoutes } from './customer-success/index.js'
import { apiGatewayModuleRoutes } from './api-gateway/index.js'
import { evsModuleRoutes } from './event-sourcing/index.js'
import { billingModuleRoutes } from './billing/index.js'
import { reportingModuleRoutes } from './reporting/index.js'
import { scmModuleRoutes } from './supply-chain/index.js'
import { qmsModuleRoutes } from './qms/index.js'
import { ppmModuleRoutes } from './ppm/index.js'
import { secAdvModuleRoutes } from './security-adv/index.js'
import { appStoreModuleRoutes } from './app-store/index.js'
import { aiStudioModuleRoutes } from './ai-studio/index.js'
import { payrollModuleRoutes } from './payroll/index.js'
import { loyaltyModuleRoutes } from './loyalty/index.js'
import { fleetModuleRoutes } from './fleet/index.js'
import { facilityModuleRoutes } from './facility/index.js'
import { knowledgeBaseModuleRoutes } from './knowledge-base/index.js'
import { budgetModuleRoutes } from './budget/index.js'
import { omsModuleRoutes } from './oms/index.js'
import { slaModuleRoutes } from './sla/index.js'
import { riskModuleRoutes } from './risk/index.js'
import { signaturesModuleRoutes } from './signatures/index.js'
import { timeAttendanceModuleRoutes } from './time-attendance/index.js'
import { surveysModuleRoutes } from './surveys/index.js'
import { productsModuleRoutes } from './products/index.js'
import { expensesModuleRoutes } from './expenses/index.js'
import { atsModuleRoutes } from './ats/index.js'
import { eventsModuleRoutes } from './events-mgmt/index.js'
import { notificationsModuleRoutes } from './notifications-hub/index.js'
import { taskBoardModuleRoutes } from './task-board/index.js'
import { invoice2ModuleRoutes } from './invoice2/index.js'
import { biDashboardModuleRoutes } from './bi-dashboard/index.js'

export async function registerRoutes(app: FastifyInstance) {
  // All REST routes are under /v1
  await app.register(
    async (v1) => {
      await v1.register(authRoutes, { prefix: '/auth' })
      await v1.register(userRoutes, { prefix: '/users' })
      await v1.register(orgRoutes, { prefix: '/org' })
      await v1.register(roleRoutes, { prefix: '/roles' })
      await v1.register(settingsRoutes, { prefix: '/settings' })
      await v1.register(auditRoutes, { prefix: '/audit-logs' })
      await v1.register(notificationRoutes, { prefix: '/notifications' })
      await v1.register(translationRoutes, { prefix: '/translations' })
      await v1.register(aiUsageRoutes, { prefix: '/ai-usage' })
      await v1.register(hrRoutes, { prefix: '/hr' })
      await v1.register(pmRoutes, { prefix: '/pm' })
      await v1.register(crmRoutes, { prefix: '/crm' })
      await v1.register(salesRoutes, { prefix: '/sales' })
      await v1.register(financeRoutes, { prefix: '/finance' })
      await v1.register(inventoryRoutes, { prefix: '/inventory' })
      await v1.register(procurementRoutes, { prefix: '/procurement' })
      await v1.register(manufacturingRoutes, { prefix: '/manufacturing' })
      await v1.register(analyticsRoutes, { prefix: '/analytics' })
      await v1.register(brainRoutes, { prefix: '/brain' })
      await v1.register(automationRoutes, { prefix: '/automation' })
      await v1.register(docsRoutes, { prefix: '/docs' })
      await v1.register(kbRoutes, { prefix: '/kb' })
      await v1.register(portalRoutes, { prefix: '/portal' })
      await v1.register(helpdeskRoutes, { prefix: '/helpdesk' })
      await v1.register(commRoutes, { prefix: '/comm' })
      await v1.register(marketplaceRoutes, { prefix: '/marketplace' })
      await v1.register(aiExecRoutes, { prefix: '/ai-exec' })
      await v1.register(securityRoutes, { prefix: '/security' })
      await v1.register(monitoringRoutes, { prefix: '/monitoring' })
      await v1.register(backupRoutes, { prefix: '/backup' })
      await v1.register(drRoutes, { prefix: '/dr' })
      await v1.register(aiSreRoutes, { prefix: '/ai-sre' })
      await v1.register(deploymentRoutes, { prefix: '/deployment' })
      await v1.register(developerRoutes, { prefix: '/developer' })
      await v1.register(adminAiProviderRoutes, { prefix: '/admin/ai' })
      await v1.register(aiWorkRoutes, { prefix: '/ai-work' })
      await v1.register(aiAgentsRoutes, { prefix: '/ai-agents' })
      await v1.register(aiOnboardingRoutes, { prefix: '/ai-onboarding' })
      await v1.register(aiWorkspaceRoutes, { prefix: '/ai-workspace' })
      await v1.register(realtimeRoutes, { prefix: '/events' })
      await v1.register(globalSearchRoutes, { prefix: '/search' })
      await v1.register(ssoModuleRoutes, { prefix: '/sso' })
      await v1.register(reportBuilderRoutes, { prefix: '/reports' })
      await v1.register(wlRoutes, { prefix: '/white-label' })
      await v1.register(cdpModuleRoutes, { prefix: '/cdp' })
      await v1.register(mktRoutes, { prefix: '/marketing' })
      await v1.register(dataHubModuleRoutes, { prefix: '/data-hub' })
      await v1.register(mobileModuleRoutes, { prefix: '/mobile' })
      await v1.register(partnerModuleRoutes, { prefix: '/partners' })
      await v1.register(forecastModuleRoutes, { prefix: '/forecasting' })
      await v1.register(fxModuleRoutes, { prefix: '/fx' })
      await v1.register(clmModuleRoutes, { prefix: '/clm' })
      await v1.register(fsmModuleRoutes, { prefix: '/fsm' })
      await v1.register(vendorModuleRoutes, { prefix: '/vendors' })
      await v1.register(lmsModuleRoutes, { prefix: '/lms' })
      await v1.register(assetModuleRoutes, { prefix: '/assets' })
      await v1.register(complianceModuleRoutes, { prefix: '/compliance' })
      await v1.register(csModuleRoutes, { prefix: '/customer-success' })
      await v1.register(apiGatewayModuleRoutes, { prefix: '/api-gateway' })
      await v1.register(evsModuleRoutes, { prefix: '/evs' })
      await v1.register(billingModuleRoutes, { prefix: '/billing' })
      await v1.register(reportingModuleRoutes, { prefix: '/reporting' })
      await v1.register(scmModuleRoutes, { prefix: '/scm' })
      await v1.register(qmsModuleRoutes, { prefix: '/qms' })
      await v1.register(ppmModuleRoutes, { prefix: '/ppm' })
      await v1.register(secAdvModuleRoutes, { prefix: '/security-adv' })
      await v1.register(appStoreModuleRoutes, { prefix: '/app-store' })
      await v1.register(aiStudioModuleRoutes, { prefix: '/ai-studio' })
      await v1.register(payrollModuleRoutes, { prefix: '/payroll' })
      await v1.register(loyaltyModuleRoutes, { prefix: '/loyalty' })
      await v1.register(fleetModuleRoutes, { prefix: '/fleet' })
      await v1.register(facilityModuleRoutes, { prefix: '/facility' })
      await v1.register(knowledgeBaseModuleRoutes, { prefix: '/knowledge-base' })
      await v1.register(budgetModuleRoutes, { prefix: '/budget' })
      await v1.register(omsModuleRoutes, { prefix: '/oms' })
      await v1.register(slaModuleRoutes, { prefix: '/sla' })
      await v1.register(riskModuleRoutes, { prefix: '/risk' })
      await v1.register(signaturesModuleRoutes, { prefix: '/signatures' })
      await v1.register(timeAttendanceModuleRoutes, { prefix: '/time-attendance' })
      await v1.register(surveysModuleRoutes, { prefix: '/surveys' })
      await v1.register(productsModuleRoutes, { prefix: '/products' })
      await v1.register(expensesModuleRoutes, { prefix: '/expenses' })
      await v1.register(atsModuleRoutes, { prefix: '/ats' })
      await v1.register(eventsModuleRoutes, { prefix: '/events-mgmt' })
      await v1.register(notificationsModuleRoutes, { prefix: '/notifications-hub' })
      await v1.register(taskBoardModuleRoutes, { prefix: '/task-board' })
      await v1.register(invoice2ModuleRoutes, { prefix: '/invoice2' })
      await v1.register(biDashboardModuleRoutes, { prefix: '/bi-dashboard' })
    },
    { prefix: '/v1' },
  )
}
