import type { FastifyInstance } from 'fastify'
import { authRoutes } from './auth.routes.js'
import { userRoutes } from './users.routes.js'
import { orgRoutes } from './org.routes.js'
import { roleRoutes } from './roles.routes.js'
import { settingsRoutes } from './settings.routes.js'
import { auditRoutes } from './audit.routes.js'
import { notificationRoutes } from './notifications.routes.js'
import { translationRoutes } from './translations.routes.js'
import { aiUsageRoutes } from './ai-usage.routes.js'
import { hrRoutes } from './hr/index.js'
import { pmRoutes } from './pm/index.js'
import { crmRoutes } from './crm/index.js'
import { salesRoutes } from './sales/index.js'
import { financeRoutes } from './finance/index.js'
import { inventoryRoutes } from './inventory/index.js'
import { procurementRoutes } from './procurement/index.js'
import { manufacturingRoutes } from './manufacturing/index.js'
import { analyticsRoutes } from './analytics/index.js'
import { brainRoutes } from './brain/index.js'
import { automationRoutes } from './automation/index.js'
import { docsRoutes } from './docs/index.js'
import { kbRoutes } from './kb/index.js'
import { portalRoutes } from './portal/index.js'
import { helpdeskRoutes } from './helpdesk/index.js'
import { commRoutes } from './comm/index.js'
import { marketplaceRoutes } from './marketplace/index.js'
import { aiExecRoutes } from './ai-exec/index.js'
import { securityRoutes } from './security/index.js'
import { monitoringRoutes } from './monitoring/index.js'
import { backupRoutes } from './backup/index.js'
import { drRoutes } from './dr/index.js'
import { aiSreRoutes } from './ai-sre/index.js'
import { deploymentRoutes } from './deployment/index.js'
import { developerRoutes } from './developer/index.js'
import { adminAiProviderRoutes } from './admin/ai-providers.routes.js'
import { aiWorkRoutes } from './ai-work/index.js'
import { aiAgentsRoutes } from './ai-agents/index.js'
import { aiOnboardingRoutes } from './ai-onboarding/index.js'
import { aiWorkspaceRoutes } from './ai-workspace/index.js'
import { realtimeRoutes } from './events/index.js'
import { globalSearchRoutes } from './search/index.js'
import { ssoModuleRoutes } from './sso/index.js'
import { reportBuilderRoutes } from './reports/index.js'
import { wlRoutes } from './whitelabel/index.js'
import { cdpModuleRoutes } from './cdp/index.js'
import { mktRoutes } from './marketing/index.js'
import { dataHubModuleRoutes } from './data-hub/index.js'
import { mobileModuleRoutes } from './mobile/index.js'
import { partnerModuleRoutes } from './partners/index.js'
import { forecastModuleRoutes } from './forecasting/index.js'
import { fxModuleRoutes } from './fx/index.js'
import { clmModuleRoutes } from './clm/index.js'
import { fsmModuleRoutes } from './fsm/index.js'
import { vendorModuleRoutes } from './vendors/index.js'
import { lmsModuleRoutes } from './lms/index.js'
import { assetModuleRoutes } from './assets/index.js'
import { complianceModuleRoutes } from './compliance/index.js'
import { csModuleRoutes } from './customer-success/index.js'
import { apiGatewayModuleRoutes } from './api-gateway/index.js'
import { evsModuleRoutes } from './event-sourcing/index.js'
import { billingModuleRoutes } from './billing/index.js'
import { reportingModuleRoutes } from './reporting/index.js'
import { scmModuleRoutes } from './supply-chain/index.js'
import { qmsModuleRoutes } from './qms/index.js'
import { ppmModuleRoutes } from './ppm/index.js'
import { secAdvModuleRoutes } from './security-adv/index.js'
import { appStoreModuleRoutes } from './app-store/index.js'
import { aiStudioModuleRoutes } from './ai-studio/index.js'
import { payrollModuleRoutes } from './payroll/index.js'
import { loyaltyModuleRoutes } from './loyalty/index.js'
import { fleetModuleRoutes } from './fleet/index.js'
import { facilityModuleRoutes } from './facility/index.js'
import { knowledgeBaseModuleRoutes } from './knowledge-base/index.js'
import { budgetModuleRoutes } from './budget/index.js'
import { omsModuleRoutes } from './oms/index.js'
import { slaModuleRoutes } from './sla/index.js'
import { riskModuleRoutes } from './risk/index.js'
import { signaturesModuleRoutes } from './signatures/index.js'
import { timeAttendanceModuleRoutes } from './time-attendance/index.js'
import { surveysModuleRoutes } from './surveys/index.js'
import { productsModuleRoutes } from './products/index.js'
import { expensesModuleRoutes } from './expenses/index.js'
import { atsModuleRoutes } from './ats/index.js'
import { eventsModuleRoutes } from './events-mgmt/index.js'
import { notificationsModuleRoutes } from './notifications-hub/index.js'
import { taskBoardModuleRoutes } from './task-board/index.js'
import { invoice2ModuleRoutes } from './invoice2/index.js'
import { biDashboardModuleRoutes } from './bi-dashboard/index.js'
import { clm2ModuleRoutes } from './clm2/index.js'
import { treasuryModuleRoutes } from './treasury/index.js'
import { ocrModuleRoutes } from './ocr/index.js'
import { supplierPortalModuleRoutes } from './supplier-portal/index.js'
import { loyalty2ModuleRoutes } from './loyalty2/index.js'
import { forecasting2ModuleRoutes } from './forecasting2/index.js'
import { complianceCalendarModuleRoutes } from './compliance-calendar/index.js'
import { identityModuleRoutes } from './identity/index.js'
import { platformHealthModuleRoutes } from './platform-health/index.js'
import { marketplace2ModuleRoutes } from './marketplace2/index.js'
import { dmsModuleRoutes } from './dms/index.js'
import { travelModuleRoutes } from './travel/index.js'
import { grantsModuleRoutes } from './grants/index.js'
import { propertyModuleRoutes } from './property/index.js'
import { iotModuleRoutes } from './iot/index.js'
import { csrModuleRoutes } from './csr/index.js'
import { innovationModuleRoutes } from './innovation/index.js'
import { sub2ModuleRoutes } from './sub2/index.js'
import { chatModuleRoutes } from './chat/index.js'
import { etlModuleRoutes } from './etl/index.js'
import { legalModuleRoutes } from './legal/index.js'
import { lms2ModuleRoutes } from './lms2/index.js'
import { healthcareModuleRoutes } from './healthcare/index.js'
import { posModuleRoutes } from './pos/index.js'
import { retailModuleRoutes } from './retail/index.js'
import { printMgmtModuleRoutes } from './print-mgmt/index.js'
import { franchiseModuleRoutes } from './franchise/index.js'
import { nonprofitModuleRoutes } from './nonprofit/index.js'
import { rdModuleRoutes } from './rd/index.js'
import { reporting3ModuleRoutes } from './reporting3/index.js'
import { energyModuleRoutes } from './energy/index.js'
import { transportModuleRoutes } from './transport/index.js'
import { insuranceModuleRoutes } from './insurance/index.js'
import { reCrmModuleRoutes } from './re-crm/index.js'
import { constructionModuleRoutes } from './construction/index.js'
import { agricultureModuleRoutes } from './agriculture/index.js'
import { marineModuleRoutes } from './marine/index.js'
import { governmentModuleRoutes } from './government/index.js'
import { meetingsModuleRoutes } from './meetings/index.js'
import { damModuleRoutes } from './dam/index.js'
import { mediaModuleRoutes } from './media/index.js'
import { educationAdminModuleRoutes } from './education-admin/index.js'
import { hospitalityModuleRoutes } from './hospitality/index.js'
import { sportsModuleRoutes } from './sports/index.js'
import { financialAdvisoryModuleRoutes } from './financial-advisory/index.js'
import { veterinaryModuleRoutes } from './veterinary/index.js'
import { wasteModuleRoutes } from './waste/index.js'
import { cemeteryModuleRoutes } from './cemetery/index.js'
import { ticketingModuleRoutes } from './ticketing/index.js'
import { automotiveModuleRoutes } from './automotive/index.js'
import { miningModuleRoutes } from './mining/index.js'
import { textileModuleRoutes } from './textile/index.js'
import { cleaningModuleRoutes } from './cleaning/index.js'
import { pestControlModuleRoutes } from './pest-control/index.js'
import { photographyModuleRoutes } from './photography/index.js'
import { musicModuleRoutes } from './music/index.js'
import { coworkingModuleRoutes } from './coworking/index.js'
import { petBoardingModuleRoutes } from './pet-boarding/index.js'
import { foodDeliveryModuleRoutes } from './food-delivery/index.js'
import { pharmacyModuleRoutes } from './pharmacy/index.js'
import { aviationModuleRoutes } from './aviation/index.js'
import { carRentalModuleRoutes } from './car-rental/index.js'
import { laundryModuleRoutes } from './laundry/index.js'
import { securityServicesModuleRoutes } from './security-services/index.js'
import { dentalModuleRoutes } from './dental/index.js'
import { architectureModuleRoutes } from './architecture/index.js'
import { conferenceModuleRoutes } from './conference/index.js'
import { publishingModuleRoutes } from './publishing/index.js'
import { fisheryModuleRoutes } from './fishery/index.js'
import { solarModuleRoutes } from './solar/index.js'
import { aiWorkspaceRoutes as aiWorkspacePhase38Routes } from './ai-workspace/phase38.js'
import { liveToolsModuleRoutes } from './live-tools/index.js'
import { aiAutonomousModuleRoutes } from './ai-autonomous/index.js'
import { personalAssistantModuleRoutes } from './personal-assistant/index.js'
import { goalsEngineModuleRoutes } from './goals-engine/index.js'
import { externalIntelligenceModuleRoutes } from './external-intelligence/index.js'
import { predictiveSimModuleRoutes } from './predictive-sim/index.js'
import { strategyOrchestratorModuleRoutes } from './strategy-orchestrator/index.js'
import { integrationHubModuleRoutes } from './integration-hub/index.js'
import { knowledgeGraphModuleRoutes } from './knowledge-graph/index.js'
import { agentsPlatformModuleRoutes } from './agents-platform/index.js'
import { actionLayerModuleRoutes } from './action-layer/index.js'
import { learningModuleRoutes } from './learning/index.js'
import { aosModuleRoutes } from './aos/index.js'
import { paeModuleRoutes } from './pae/index.js'
import { adiModuleRoutes } from './adi/index.js'
import { mchModuleRoutes } from './mch/index.js'
import { pccModuleRoutes } from './pcc/index.js'
import { apaModuleRoutes } from './apa/index.js'
import { cspModuleRoutes } from './csp/index.js'

export async function registerRoutes(app: FastifyInstance) {
  // All REST routes are under /v1
  await app.register(
    async (v1) => {
      await v1.register(authRoutes, { prefix: '/auth' })
      await v1.register(userRoutes, { prefix: '/users' })
      await v1.register(orgRoutes, { prefix: '/org' })
      await v1.register(roleRoutes, { prefix: '/roles' })
      await v1.register(settingsRoutes, { prefix: '/settings' })
      await v1.register(auditRoutes, { prefix: '/audit-logs' })
      await v1.register(notificationRoutes, { prefix: '/notifications' })
      await v1.register(translationRoutes, { prefix: '/translations' })
      await v1.register(aiUsageRoutes, { prefix: '/ai-usage' })
      await v1.register(hrRoutes, { prefix: '/hr' })
      await v1.register(pmRoutes, { prefix: '/pm' })
      await v1.register(crmRoutes, { prefix: '/crm' })
      await v1.register(salesRoutes, { prefix: '/sales' })
      await v1.register(financeRoutes, { prefix: '/finance' })
      await v1.register(inventoryRoutes, { prefix: '/inventory' })
      await v1.register(procurementRoutes, { prefix: '/procurement' })
      await v1.register(manufacturingRoutes, { prefix: '/manufacturing' })
      await v1.register(analyticsRoutes, { prefix: '/analytics' })
      await v1.register(brainRoutes, { prefix: '/brain' })
      await v1.register(automationRoutes, { prefix: '/automation' })
      await v1.register(docsRoutes, { prefix: '/docs' })
      await v1.register(kbRoutes, { prefix: '/kb' })
      await v1.register(portalRoutes, { prefix: '/portal' })
      await v1.register(helpdeskRoutes, { prefix: '/helpdesk' })
      await v1.register(commRoutes, { prefix: '/comm' })
      await v1.register(marketplaceRoutes, { prefix: '/marketplace' })
      await v1.register(aiExecRoutes, { prefix: '/ai-exec' })
      await v1.register(securityRoutes, { prefix: '/security' })
      await v1.register(monitoringRoutes, { prefix: '/monitoring' })
      await v1.register(backupRoutes, { prefix: '/backup' })
      await v1.register(drRoutes, { prefix: '/dr' })
      await v1.register(aiSreRoutes, { prefix: '/ai-sre' })
      await v1.register(deploymentRoutes, { prefix: '/deployment' })
      await v1.register(developerRoutes, { prefix: '/developer' })
      await v1.register(adminAiProviderRoutes, { prefix: '/admin/ai' })
      await v1.register(aiWorkRoutes, { prefix: '/ai-work' })
      await v1.register(aiAgentsRoutes, { prefix: '/ai-agents' })
      await v1.register(aiOnboardingRoutes, { prefix: '/ai-onboarding' })
      await v1.register(aiWorkspaceRoutes, { prefix: '/ai-workspace' })
      await v1.register(realtimeRoutes, { prefix: '/events' })
      await v1.register(globalSearchRoutes, { prefix: '/search' })
      await v1.register(ssoModuleRoutes, { prefix: '/sso' })
      await v1.register(reportBuilderRoutes, { prefix: '/reports' })
      await v1.register(wlRoutes, { prefix: '/white-label' })
      await v1.register(cdpModuleRoutes, { prefix: '/cdp' })
      await v1.register(mktRoutes, { prefix: '/marketing' })
      await v1.register(dataHubModuleRoutes, { prefix: '/data-hub' })
      await v1.register(mobileModuleRoutes, { prefix: '/mobile' })
      await v1.register(partnerModuleRoutes, { prefix: '/partners' })
      await v1.register(forecastModuleRoutes, { prefix: '/forecasting' })
      await v1.register(fxModuleRoutes, { prefix: '/fx' })
      await v1.register(clmModuleRoutes, { prefix: '/clm' })
      await v1.register(fsmModuleRoutes, { prefix: '/fsm' })
      await v1.register(vendorModuleRoutes, { prefix: '/vendors' })
      await v1.register(lmsModuleRoutes, { prefix: '/lms' })
      await v1.register(assetModuleRoutes, { prefix: '/assets' })
      await v1.register(complianceModuleRoutes, { prefix: '/compliance' })
      await v1.register(csModuleRoutes, { prefix: '/customer-success' })
      await v1.register(apiGatewayModuleRoutes, { prefix: '/api-gateway' })
      await v1.register(evsModuleRoutes, { prefix: '/evs' })
      await v1.register(billingModuleRoutes, { prefix: '/billing' })
      await v1.register(reportingModuleRoutes, { prefix: '/reporting' })
      await v1.register(scmModuleRoutes, { prefix: '/scm' })
      await v1.register(qmsModuleRoutes, { prefix: '/qms' })
      await v1.register(ppmModuleRoutes, { prefix: '/ppm' })
      await v1.register(secAdvModuleRoutes, { prefix: '/security-adv' })
      await v1.register(appStoreModuleRoutes, { prefix: '/app-store' })
      await v1.register(aiStudioModuleRoutes, { prefix: '/ai-studio' })
      await v1.register(payrollModuleRoutes, { prefix: '/payroll' })
      await v1.register(loyaltyModuleRoutes, { prefix: '/loyalty' })
      await v1.register(fleetModuleRoutes, { prefix: '/fleet' })
      await v1.register(facilityModuleRoutes, { prefix: '/facility' })
      await v1.register(knowledgeBaseModuleRoutes, { prefix: '/knowledge-base' })
      await v1.register(budgetModuleRoutes, { prefix: '/budget' })
      await v1.register(omsModuleRoutes, { prefix: '/oms' })
      await v1.register(slaModuleRoutes, { prefix: '/sla' })
      await v1.register(riskModuleRoutes, { prefix: '/risk' })
      await v1.register(signaturesModuleRoutes, { prefix: '/signatures' })
      await v1.register(timeAttendanceModuleRoutes, { prefix: '/time-attendance' })
      await v1.register(surveysModuleRoutes, { prefix: '/surveys' })
      await v1.register(productsModuleRoutes, { prefix: '/products' })
      await v1.register(expensesModuleRoutes, { prefix: '/expenses' })
      await v1.register(atsModuleRoutes, { prefix: '/ats' })
      await v1.register(eventsModuleRoutes, { prefix: '/events-mgmt' })
      await v1.register(notificationsModuleRoutes, { prefix: '/notifications-hub' })
      await v1.register(taskBoardModuleRoutes, { prefix: '/task-board' })
      await v1.register(invoice2ModuleRoutes, { prefix: '/invoice2' })
      await v1.register(biDashboardModuleRoutes, { prefix: '/bi-dashboard' })
      await v1.register(clm2ModuleRoutes, { prefix: '/clm2' })
      await v1.register(treasuryModuleRoutes, { prefix: '/treasury' })
      await v1.register(ocrModuleRoutes, { prefix: '/ocr' })
      await v1.register(supplierPortalModuleRoutes, { prefix: '/suppliers' })
      await v1.register(loyalty2ModuleRoutes, { prefix: '/loyalty2' })
      await v1.register(forecasting2ModuleRoutes, { prefix: '/forecasting2' })
      await v1.register(complianceCalendarModuleRoutes, { prefix: '/compliance-calendar' })
      await v1.register(identityModuleRoutes, { prefix: '/identity' })
      await v1.register(platformHealthModuleRoutes, { prefix: '/platform-health' })
      await v1.register(marketplace2ModuleRoutes, { prefix: '/marketplace2' })
      await v1.register(dmsModuleRoutes, { prefix: '/dms' })
      await v1.register(travelModuleRoutes, { prefix: '/travel' })
      await v1.register(grantsModuleRoutes, { prefix: '/grants' })
      await v1.register(propertyModuleRoutes, { prefix: '/property' })
      await v1.register(iotModuleRoutes, { prefix: '/iot' })
      await v1.register(csrModuleRoutes, { prefix: '/csr' })
      await v1.register(innovationModuleRoutes, { prefix: '/innovation' })
      await v1.register(sub2ModuleRoutes, { prefix: '/sub2' })
      await v1.register(chatModuleRoutes, { prefix: '/chat' })
      await v1.register(etlModuleRoutes, { prefix: '/etl' })
      await v1.register(legalModuleRoutes, { prefix: '/legal' })
      await v1.register(lms2ModuleRoutes, { prefix: '/lms2' })
      await v1.register(healthcareModuleRoutes, { prefix: '/healthcare' })
      await v1.register(posModuleRoutes, { prefix: '/pos' })
      await v1.register(retailModuleRoutes, { prefix: '/retail' })
      await v1.register(printMgmtModuleRoutes, { prefix: '/print-mgmt' })
      await v1.register(franchiseModuleRoutes, { prefix: '/franchise' })
      await v1.register(nonprofitModuleRoutes, { prefix: '/nonprofit' })
      await v1.register(rdModuleRoutes, { prefix: '/rd' })
      await v1.register(reporting3ModuleRoutes, { prefix: '/reporting3' })
      await v1.register(energyModuleRoutes, { prefix: '/energy' })
      await v1.register(transportModuleRoutes, { prefix: '/transport' })
      await v1.register(insuranceModuleRoutes, { prefix: '/insurance' })
      await v1.register(reCrmModuleRoutes, { prefix: '/re-crm' })
      await v1.register(constructionModuleRoutes, { prefix: '/construction' })
      await v1.register(agricultureModuleRoutes, { prefix: '/agriculture' })
      await v1.register(marineModuleRoutes, { prefix: '/marine' })
      await v1.register(governmentModuleRoutes, { prefix: '/government' })
      await v1.register(meetingsModuleRoutes, { prefix: '/meetings' })
      await v1.register(damModuleRoutes, { prefix: '/dam' })
      await v1.register(mediaModuleRoutes, { prefix: '/media' })
      await v1.register(educationAdminModuleRoutes, { prefix: '/education' })
      await v1.register(hospitalityModuleRoutes, { prefix: '/hospitality' })
      await v1.register(sportsModuleRoutes, { prefix: '/sports' })
      await v1.register(financialAdvisoryModuleRoutes, { prefix: '/financial-advisory' })
      await v1.register(veterinaryModuleRoutes, { prefix: '/veterinary' })
      await v1.register(wasteModuleRoutes, { prefix: '/waste' })
      await v1.register(cemeteryModuleRoutes, { prefix: '/cemetery' })
      await v1.register(ticketingModuleRoutes, { prefix: '/ticketing' })
      await v1.register(automotiveModuleRoutes, { prefix: '/automotive' })
      await v1.register(miningModuleRoutes, { prefix: '/mining' })
      await v1.register(textileModuleRoutes, { prefix: '/textile' })
      await v1.register(cleaningModuleRoutes, { prefix: '/cleaning' })
      await v1.register(pestControlModuleRoutes, { prefix: '/pest-control' })
      await v1.register(photographyModuleRoutes, { prefix: '/photography' })
      await v1.register(musicModuleRoutes, { prefix: '/music' })
      await v1.register(coworkingModuleRoutes, { prefix: '/coworking' })
      await v1.register(petBoardingModuleRoutes, { prefix: '/pet-boarding' })
      await v1.register(foodDeliveryModuleRoutes, { prefix: '/food-delivery' })
      await v1.register(pharmacyModuleRoutes, { prefix: '/pharmacy' })
      await v1.register(aviationModuleRoutes, { prefix: '/aviation' })
      await v1.register(carRentalModuleRoutes, { prefix: '/car-rental' })
      await v1.register(laundryModuleRoutes, { prefix: '/laundry' })
      await v1.register(securityServicesModuleRoutes, { prefix: '/security-services' })
      await v1.register(dentalModuleRoutes, { prefix: '/dental' })
      await v1.register(architectureModuleRoutes, { prefix: '/architecture' })
      await v1.register(conferenceModuleRoutes, { prefix: '/conference' })
      await v1.register(publishingModuleRoutes, { prefix: '/publishing' })
      await v1.register(fisheryModuleRoutes, { prefix: '/fishery' })
      await v1.register(solarModuleRoutes, { prefix: '/solar' })
      await v1.register(aiWorkspacePhase38Routes, { prefix: '/ai-workspace' })
      await v1.register(liveToolsModuleRoutes, { prefix: '' })
      await v1.register(aiAutonomousModuleRoutes, { prefix: '' })
      await v1.register(personalAssistantModuleRoutes, { prefix: '' })
      await v1.register(goalsEngineModuleRoutes, { prefix: '' })
      await v1.register(externalIntelligenceModuleRoutes, { prefix: '' })
      await v1.register(predictiveSimModuleRoutes, { prefix: '' })
      await v1.register(strategyOrchestratorModuleRoutes, { prefix: '' })
      await v1.register(integrationHubModuleRoutes, { prefix: '' })
      await v1.register(knowledgeGraphModuleRoutes, { prefix: '' })
      await v1.register(agentsPlatformModuleRoutes, { prefix: '' })
      await v1.register(actionLayerModuleRoutes, { prefix: '' })
      await v1.register(learningModuleRoutes, { prefix: '' })
      await v1.register(aosModuleRoutes, { prefix: '' })
      await v1.register(paeModuleRoutes, { prefix: '' })
      await v1.register(adiModuleRoutes, { prefix: '' })
      await v1.register(mchModuleRoutes, { prefix: '' })
      await v1.register(pccModuleRoutes, { prefix: '' })
      await v1.register(apaModuleRoutes, { prefix: '' })
      await v1.register(cspModuleRoutes, { prefix: '' })
    },
    { prefix: '/v1' },
  )
}
