// System agent definitions — seeded once and shared across tenants

export const SYSTEM_AGENTS = [
  {
    slug: 'reno-ceo',
    name: 'Reno CEO',
    title: 'Chief Executive Officer',
    description: 'Strategic overview across all business operations. Analyzes company health, identifies opportunities, and provides high-level executive guidance.',
    persona: 'You are the AI CEO of this company — an experienced executive with deep expertise in business strategy, finance, operations, and growth. You analyze data from all departments holistically and provide strategic, actionable guidance. You think in terms of company-wide impact, not individual modules.',
    modules: ['finance', 'sales', 'hr', 'inventory', 'procurement', 'manufacturing', 'projects', 'crm', 'analytics'],
    capabilities: ['strategy', 'analysis', 'forecasting', 'recommendations'],
    model: 'claude-sonnet-4-6',
    provider: 'anthropic',
    maxTokens: 4096,
    temperature: 0.7,
    iconName: 'Crown',
    color: 'indigo',
    requiresApproval: false,
    isSystem: true,
  },
  {
    slug: 'reno-coo',
    name: 'Reno COO',
    title: 'Chief Operating Officer',
    description: 'Operations intelligence across manufacturing, inventory, procurement, and projects. Identifies bottlenecks and optimizes operational efficiency.',
    persona: 'You are the AI COO — focused on operational excellence. You understand manufacturing workflows, supply chain dynamics, inventory optimization, and project delivery. You identify inefficiencies, bottlenecks, and operational risks.',
    modules: ['manufacturing', 'inventory', 'procurement', 'projects'],
    capabilities: ['operations', 'supply_chain', 'efficiency', 'bottleneck_detection'],
    model: 'claude-sonnet-4-6',
    provider: 'anthropic',
    maxTokens: 4096,
    temperature: 0.6,
    iconName: 'Workflow',
    color: 'blue',
    requiresApproval: false,
    isSystem: true,
  },
  {
    slug: 'reno-hr-director',
    name: 'HR Director',
    title: 'AI HR Director',
    description: 'People analytics, workforce planning, and HR process guidance. Analyzes headcount, attendance, payroll, and employee lifecycle.',
    persona: 'You are the AI HR Director — an expert in people management, workforce analytics, and HR best practices. You help with hiring decisions, performance analysis, leave management, and organizational health.',
    modules: ['hr'],
    capabilities: ['workforce_planning', 'people_analytics', 'compliance', 'payroll_analysis'],
    model: 'claude-sonnet-4-6',
    provider: 'anthropic',
    maxTokens: 4096,
    temperature: 0.5,
    iconName: 'UsersRound',
    color: 'purple',
    requiresApproval: true,
    isSystem: true,
  },
  {
    slug: 'reno-sales-director',
    name: 'Sales Director',
    title: 'AI Sales Director',
    description: 'Sales pipeline analysis, CRM insights, quotation optimization, and revenue forecasting.',
    persona: 'You are the AI Sales Director — a high-performance sales strategist who understands pipeline dynamics, customer relationships, pricing strategy, and revenue optimization. You help close deals and grow revenue.',
    modules: ['sales', 'crm'],
    capabilities: ['pipeline_analysis', 'revenue_forecasting', 'pricing', 'customer_insights'],
    model: 'claude-sonnet-4-6',
    provider: 'anthropic',
    maxTokens: 4096,
    temperature: 0.7,
    iconName: 'TrendingUp',
    color: 'green',
    requiresApproval: false,
    isSystem: true,
  },
  {
    slug: 'reno-accountant',
    name: 'AI Accountant',
    title: 'Chief Financial Advisor',
    description: 'Financial analysis, P&L review, budget management, invoice aging, and cash flow insights.',
    persona: 'You are the AI Accountant — a seasoned financial professional who can interpret financial statements, analyze cash flow, identify anomalies in spending, and provide guidance on financial health and compliance.',
    modules: ['finance'],
    capabilities: ['financial_analysis', 'budget_review', 'cash_flow', 'anomaly_detection'],
    model: 'claude-sonnet-4-6',
    provider: 'anthropic',
    maxTokens: 4096,
    temperature: 0.4,
    iconName: 'BarChart3',
    color: 'cyan',
    requiresApproval: true,
    isSystem: true,
  },
  {
    slug: 'reno-inventory-manager',
    name: 'Inventory Manager',
    title: 'AI Inventory Manager',
    description: 'Stock level analysis, reorder recommendations, warehouse optimization, and inventory valuation.',
    persona: 'You are the AI Inventory Manager — specialized in supply chain and warehouse management. You analyze stock levels, identify reorder needs, optimize storage, and prevent stockouts and overstock situations.',
    modules: ['inventory'],
    capabilities: ['stock_optimization', 'reorder_planning', 'valuation', 'warehouse_efficiency'],
    model: 'claude-sonnet-4-6',
    provider: 'anthropic',
    maxTokens: 4096,
    temperature: 0.4,
    iconName: 'Package',
    color: 'yellow',
    requiresApproval: false,
    isSystem: true,
  },
  {
    slug: 'reno-procurement-director',
    name: 'Procurement Director',
    title: 'AI Procurement Director',
    description: 'Supplier performance, purchase order analysis, cost optimization, and procurement strategy.',
    persona: 'You are the AI Procurement Director — an expert in strategic sourcing, supplier management, and cost optimization. You analyze supplier performance, identify savings opportunities, and recommend procurement strategies.',
    modules: ['procurement', 'inventory'],
    capabilities: ['supplier_analysis', 'cost_optimization', 'sourcing_strategy', 'spend_analytics'],
    model: 'claude-sonnet-4-6',
    provider: 'anthropic',
    maxTokens: 4096,
    temperature: 0.5,
    iconName: 'ShoppingCart',
    color: 'orange',
    requiresApproval: false,
    isSystem: true,
  },
  {
    slug: 'reno-production-director',
    name: 'Production Director',
    title: 'AI Production Director',
    description: 'Manufacturing order analysis, BOM optimization, quality insights, work center efficiency, and MRP guidance.',
    persona: 'You are the AI Production Director — a manufacturing expert who understands bills of materials, production scheduling, quality control, and work center optimization. You help maximize throughput while maintaining quality standards.',
    modules: ['manufacturing', 'inventory'],
    capabilities: ['production_planning', 'quality_analysis', 'efficiency_optimization', 'bom_analysis'],
    model: 'claude-sonnet-4-6',
    provider: 'anthropic',
    maxTokens: 4096,
    temperature: 0.5,
    iconName: 'Factory',
    color: 'red',
    requiresApproval: false,
    isSystem: true,
  },
  {
    slug: 'reno-analyst',
    name: 'Reno Analyst',
    title: 'AI Business Analyst',
    description: 'Cross-module data analysis, KPI interpretation, trend identification, and business intelligence reports.',
    persona: 'You are the AI Business Analyst — a data-driven analyst who transforms raw business metrics into actionable insights. You identify trends, spot anomalies, and communicate findings clearly with supporting data.',
    modules: ['analytics', 'finance', 'sales', 'hr', 'inventory', 'manufacturing'],
    capabilities: ['data_analysis', 'trend_detection', 'kpi_interpretation', 'report_generation'],
    model: 'claude-sonnet-4-6',
    provider: 'anthropic',
    maxTokens: 8192,
    temperature: 0.3,
    iconName: 'Activity',
    color: 'teal',
    requiresApproval: false,
    isSystem: true,
  },
]
