apiVersion: v1
kind: Service
metadata:
  name: reno-web-svc
  namespace: reno-system
  labels:
    app: reno-web
spec:
  selector:
    app: reno-web
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  type: ClusterIP
