#!/usr/bin/env bash
# Blue-Green traffic switch for Nginx upstream.
# Switches the active slot (blue | green) by rewriting the Nginx upstream
# and reloading Nginx — zero downtime.
# Usage: ./scripts/blue-green-switch.sh <blue|green>
set -euo pipefail

SLOT="${1:-}"
NGINX_CONF="${NGINX_CONF:-/etc/nginx/conf.d/reno-upstream.conf}"

if [ "$SLOT" != "blue" ] && [ "$SLOT" != "green" ]; then
  echo "Usage: $0 <blue|green>"
  exit 1
fi

# Port convention: blue=4000, green=4001
if [ "$SLOT" = "blue" ]; then
  ACTIVE_PORT=4000
  STANDBY_PORT=4001
else
  ACTIVE_PORT=4001
  STANDBY_PORT=4000
fi

echo ""
echo "============================================================"
echo "  Blue-Green Switch"
echo "  Active slot : ${SLOT} (port ${ACTIVE_PORT})"
echo "  Standby     : $([ "$SLOT" = "blue" ] && echo green || echo blue) (port ${STANDBY_PORT})"
echo "============================================================"

# Health-check the target slot before switching
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo ""
echo ">>> Health-checking ${SLOT} slot on port ${ACTIVE_PORT}..."
bash "${SCRIPT_DIR}/health-check.sh" "http://localhost:${ACTIVE_PORT}" 12 5

echo ""
echo ">>> Writing Nginx upstream config..."
cat > "${NGINX_CONF}" <<EOF
# Auto-generated by blue-green-switch.sh — active slot: ${SLOT}
upstream reno_api {
    server 127.0.0.1:${ACTIVE_PORT};
}
EOF

echo ""
echo ">>> Reloading Nginx..."
nginx -t && nginx -s reload

echo ""
echo ">>> Switch complete. Active: ${SLOT} (port ${ACTIVE_PORT})"
