export { prisma, createTenantClient, PrismaClient } from './client.js'
export type { TenantPrismaClient } from './client.js'
export type {
  CoreTenant,
  CoreCompany,
  CoreBranch,
  CoreDepartment,
  CoreTeam,
  CoreUser,
  CoreUserProfile,
  CoreUserMembership,
  CoreRole,
  CorePermission,
  CoreRolePermission,
  CoreUserRole,
  CoreUserPermissionOverride,
  CoreSession,
  SysAuditLog,
  SysNotification,
  SysSetting,
  SysBranding,
  SysJob,
  SysFeatureFlag,
  SysApiKey,
  SysTranslation,
  SysUiTranslation,
  AiUsageLog,
  BkpJob,
  BkpSnapshot,
  BkpRestoreTest,
  BkpReplication,
  BkpSchedule,
  DrPlaybook,
  DrPlaybookExecution,
  DrReadinessScore,
  AiSreIncident,
  DepDeploymentLog,
} from './generated/prisma/index.js'
